namespace Diten.CrmService.Application.Features.Territory.Contract;

/// <summary>MOD-0151 contract surface (bundle version, feature flags, reference readiness, permissions, limitations).
/// Mirrors the MOD-0149/0150 contract-parity endpoint. FU01 exposes only TerritoryModel + TerritoryNode.</summary>
public sealed record TerritoryContractDto(
    string ModuleId,
    string ModuleName,
    string Service,
    string RuntimeScope,
    Guid TenantId,
    bool IsReady,
    TerritoryFeatureFlags Features,
    IReadOnlyList<TerritoryReferenceSetReadiness> RequiredReferenceSets,
    IReadOnlyList<string> MissingRequiredReferenceSets,
    IReadOnlyList<string> Permissions,
    IReadOnlyList<string> Limitations);

/// <summary>Shipped capability flags. Everything beyond the current FU is intentionally false (later FUs).</summary>
public sealed record TerritoryFeatureFlags(
    bool TerritoryModels,
    bool TerritoryNodes,
    bool AssignmentRules,
    bool AccountAssignmentApply,
    bool ResourceAssignments,
    bool WorkflowActivation,
    bool EvidencePack,
    bool ImportExport,
    bool UiEnabled,
    bool SupportsLifecycleActions,
    bool SupportsComputedExpiry,
    bool SupportsDraftSoftDelete,
    bool SupportsWorkflowActivation,
    bool SupportsApprovalTrace,
    bool SupportsAssignmentRules,
    bool SupportsAssignmentPreview,
    bool SupportsAccountAssignmentApply,
    bool SupportsAssignmentHistory,
    bool SupportsCoverageSummary,
    bool SupportsCoverageSummaryModelLifecycleGuard,
    bool SupportsResourceAssignments,
    bool SupportsResourceExclusivityGuard,
    bool SupportsResourceAssignmentLifecycle,
    bool SupportsResourceReplacement,
    bool SupportsResourceTransfer,
    bool SupportsCurrentResponsibility,
    bool SupportsPositionBasedResourceAssignment,
    bool SupportsResourceAssignmentPlanSnapshot,
    bool SupportsResourceAssignmentPlanVsCurrent,
    bool SupportsTerritoryExport,
    bool SupportsTerritoryImportExport,
    bool SupportsTerritoryImportDryRun,
    bool SupportsTerritoryImportApply,
    bool SupportsResourceAssignmentImportApply,
    bool SupportsVisitRouteReadiness,
    bool SupportsContactDerivedCoverageReadiness,
    bool SupportsRouteCandidateReadiness,
    bool SupportsContactAvailabilityInputBoundary,
    bool SupportsVisitFrequencyInputBoundary,
    bool SupportsFrequencyProviderIntegration)
{
    /// <summary>The capabilities shipped up to and including FU05 (plus the FU04B read surfaces and the FU05A
    /// current-coverage lifecycle guard).</summary>
    public static TerritoryFeatureFlags Current => new(
        TerritoryModels: true,
        TerritoryNodes: true,
        AssignmentRules: true,
        AccountAssignmentApply: true,
        ResourceAssignments: true,
        WorkflowActivation: false,
        EvidencePack: false,
        ImportExport: false,
        UiEnabled: true,
        SupportsLifecycleActions: true,
        SupportsComputedExpiry: true,
        SupportsDraftSoftDelete: true,
        SupportsWorkflowActivation: false,
        SupportsApprovalTrace: false,
        SupportsAssignmentRules: true,
        SupportsAssignmentPreview: true,
        SupportsAccountAssignmentApply: true,
        SupportsAssignmentHistory: true,
        SupportsCoverageSummary: true,
        SupportsCoverageSummaryModelLifecycleGuard: true,
        SupportsResourceAssignments: true,
        SupportsResourceExclusivityGuard: true,
        SupportsResourceAssignmentLifecycle: true,
        SupportsResourceReplacement: true,
        SupportsResourceTransfer: true,
        SupportsCurrentResponsibility: true,
        SupportsPositionBasedResourceAssignment: true,
        SupportsResourceAssignmentPlanSnapshot: true,
        SupportsResourceAssignmentPlanVsCurrent: true,
        // FU08 — controlled XLSX import/export. ResourceAssignment APPLY stays false on purpose: the sheet is
        // exported, templated and dry-run validated, but applying it would bypass the FU04A planned/active,
        // replacement and transfer contract, so it is a separately authorized FU08A.
        SupportsTerritoryExport: true,
        SupportsTerritoryImportExport: true,
        SupportsTerritoryImportDryRun: true,
        SupportsTerritoryImportApply: true,
        SupportsResourceAssignmentImportApply: false,
        SupportsVisitRouteReadiness: true,
        SupportsContactDerivedCoverageReadiness: true,
        SupportsRouteCandidateReadiness: true,
        SupportsContactAvailabilityInputBoundary: true,
        SupportsVisitFrequencyInputBoundary: true,
        // FU09B — route-candidate readiness now consumes the MOD-0165 FU03 frequency resolve provider (read-only).
        SupportsFrequencyProviderIntegration: true);
}
