namespace Diten.ManagementGovernanceService.Application.Modules.ProcessModeling.Catalog;
internal sealed class ArchiveProcessArchitectureHandler(ICatalogStore store) : CatalogCommandHandler<ArchiveProcessArchitectureCommand>(store);
