namespace Diten.ManagementGovernanceService.Application.Modules.ProcessModeling.Catalog;
internal sealed class CreateProcessArchitectureHandler(ICatalogStore store) : CatalogCommandHandler<CreateProcessArchitectureCommand>(store);
