<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Diten.Platform.API</RootNamespace>
    <UserSecretsId>587d48b8-25d7-414f-a302-fe1078fb12ea</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diten.Platform.Application\Diten.Platform.Application.csproj" />
    <ProjectReference Include="..\Diten.Platform.Infrastructure\Diten.Platform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
