using System.Diagnostics;
using Diten.ManagementGovernanceService.Application;
using Diten.ManagementGovernanceService.Application.Modules.Dws;
using Diten.ManagementGovernanceService.Domain.Modules.Dws;
using Diten.ManagementGovernanceService.Infrastructure;
using Diten.ManagementGovernanceService.Infrastructure.Modules.Dws;
using Diten.ManagementGovernanceService.Persistence;
using Diten.ManagementGovernanceService.Persistence.Modules.Dws;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Diten.ManagementGovernanceService.ArchitectureTests.Modules.Dws;

public sealed class DwsArchitectureTests
{
    public static IEnumerable<object[]> IsolationEvidence()=>ImmutableEvidence().Select(x=>new object[]{x.Sibling,x.Dimension,x.Path,x.RequiredText});

    [Theory]
    [MemberData(nameof(IsolationEvidence))]
    public void Exact_twelve_dimensions_are_executable_for_each_sibling(DwsSiblingEvidence sibling,DwsIsolationDimension dimension,string path,string requiredText)
    {
        var blob=GitShow(sibling.ImmutableCheckpoint,path);Assert.Contains(requiredText,blob,StringComparison.Ordinal);Assert.StartsWith("services/Diten.ManagementGovernanceService/",path,StringComparison.Ordinal);
        var assemblies=new[]{typeof(StructureDefinition).Assembly,typeof(DwsAuthorizationManifest).Assembly,typeof(DwsPersistenceOwnershipManifest).Assembly,typeof(DwsInfrastructureBoundary).Assembly};var allTypes=assemblies.SelectMany(x=>x.GetTypes()).ToArray();
        switch(dimension)
        {
            case DwsIsolationDimension.ProjectGraph:Assert.All(assemblies.SelectMany(x=>x.GetReferencedAssemblies()),x=>Assert.DoesNotContain(sibling.Name,x.Name!,StringComparison.Ordinal));break;
            case DwsIsolationDimension.TypeNamespace:Assert.DoesNotContain(allTypes,x=>x.FullName?.Contains($"Modules.{sibling.Name}",StringComparison.Ordinal)==true);break;
            case DwsIsolationDimension.DependencyInjection:var services=new ServiceCollection();services.AddDwsApplication().AddDwsPersistence().AddDwsInfrastructure();Assert.DoesNotContain(services,x=>(x.ServiceType.FullName??"").Contains(sibling.Name,StringComparison.Ordinal)||(x.ImplementationType?.FullName??"").Contains(sibling.Name,StringComparison.Ordinal));break;
            case DwsIsolationDimension.Repository:Assert.DoesNotContain(typeof(DwsPersistenceOwnershipManifest).Assembly.GetTypes(),x=>x.Name.Contains(sibling.Name,StringComparison.Ordinal));break;
            case DwsIsolationDimension.CollectionIndex:Assert.All(DwsPersistenceOwnershipManifest.Collections,x=>{Assert.StartsWith("mg_dws_",x.Name);Assert.DoesNotContain(sibling.CollectionPrefix,x.Name,StringComparison.Ordinal);});break;
            case DwsIsolationDimension.EntityBase:Assert.All(new[]{typeof(StructureDefinition),typeof(StructureRevision),typeof(StructureNode),typeof(StructuralDependency),typeof(StructureBaseline)},x=>Assert.True(x.IsSubclassOf(typeof(DwsTenantEntity))));break;
            case DwsIsolationDimension.Permission:Assert.All(DwsAuthorizationManifest.Entries,x=>{Assert.StartsWith("management-governance.dws.",x.Permission);Assert.DoesNotContain(sibling.PermissionPrefix,x.Permission,StringComparison.Ordinal);});break;
            case DwsIsolationDimension.AuditOutbox:Assert.Equal(["mg_dws_audit_intents","mg_dws_outbox_messages"],DwsPersistenceOwnershipManifest.Collections.Where(x=>x.Owner is "AuditIntent" or "OutboxMessage").Select(x=>x.Name));break;
            case DwsIsolationDimension.Contract:Assert.All(typeof(DwsAuthorizationManifest).Assembly.GetTypes().Where(x=>x.Namespace?.Contains("Modules.Dws",StringComparison.Ordinal)==true),x=>Assert.DoesNotContain(sibling.Name,x.FullName!,StringComparison.Ordinal));break;
            case DwsIsolationDimension.SessionTransaction:Assert.All(DwsPersistenceOwnershipManifest.Transactions.SelectMany(x=>x.BusinessCollections),x=>Assert.DoesNotContain(sibling.CollectionPrefix,x,StringComparison.Ordinal));break;
            case DwsIsolationDimension.MigrationBootstrap:Assert.DoesNotContain(allTypes,x=>(x.Name.Contains("Migration")||x.Name.Contains("Bootstrap"))&&(x.FullName??"").Contains(sibling.Name,StringComparison.Ordinal));break;
            case DwsIsolationDimension.NegativeGuard:Assert.False(DwsInfrastructureBoundary.RuntimeActivationEnabled);Assert.Contains(sibling.ModuleRoot,path,StringComparison.OrdinalIgnoreCase);Assert.NotEmpty(sibling.AssemblyPrefix);break;
            default:throw new ArgumentOutOfRangeException(nameof(dimension));
        }
    }

    [Fact] public void Evidence_matrix_is_exact_twenty_four_and_manifest_bound(){Assert.Equal(2,DwsIsolationEvidenceManifest.Siblings.Count);Assert.Equal(24,DwsIsolationEvidenceManifest.ExactEvidence.Count);Assert.Equal(24,ImmutableEvidence().Count);Assert.Equal(["ProcessModeling","DecisionRegistry"],DwsIsolationEvidenceManifest.Siblings.Select(x=>x.Name));}
    [Fact] public void Domain_entities_have_no_task_approval_or_execution_fields(){var forbidden=new[]{"Status","Progress","DueDate","AssignedTo","Owner","ApprovedAt","ApprovedBy","Lag","CriticalPath"};var props=typeof(StructureDefinition).Assembly.GetTypes().Where(x=>x.Namespace?.Contains("Modules.Dws",StringComparison.Ordinal)==true).SelectMany(x=>x.GetProperties()).Select(x=>x.Name);Assert.DoesNotContain(props,x=>forbidden.Contains(x,StringComparer.Ordinal));}
    [Fact] public void Compile_only_boundary_never_activates_runtime(){var program=File.ReadAllText(Path.Combine(FindRoot(),"services/Diten.ManagementGovernanceService/src/Diten.ManagementGovernanceService.Api/Program.cs"));Assert.False(DwsInfrastructureBoundary.RuntimeActivationEnabled);Assert.DoesNotContain("Run(",program,StringComparison.Ordinal);Assert.DoesNotContain("Mongo",program,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("27017",program,StringComparison.Ordinal);Assert.DoesNotContain("Map",program,StringComparison.Ordinal);}

    private sealed record BlobEvidence(DwsSiblingEvidence Sibling,DwsIsolationDimension Dimension,string Path,string RequiredText);
    private static IReadOnlyList<BlobEvidence> ImmutableEvidence()
    {
        var process=DwsIsolationEvidenceManifest.Siblings.Single(x=>x.Name=="ProcessModeling");var registry=DwsIsolationEvidenceManifest.Siblings.Single(x=>x.Name=="DecisionRegistry");var p="services/Diten.ManagementGovernanceService/";var result=new List<BlobEvidence>();
        void Add(DwsSiblingEvidence sibling,DwsIsolationDimension dimension,string path,string token)=>result.Add(new(sibling,dimension,p+path,token));
        Add(process,DwsIsolationDimension.ProjectGraph,"Diten.ManagementGovernanceService.sln","Diten.ManagementGovernanceService.Domain");Add(process,DwsIsolationDimension.TypeNamespace,"src/Diten.ManagementGovernanceService.Domain/Modules/ProcessModeling/ProcessModels.cs","Modules.ProcessModeling");Add(process,DwsIsolationDimension.DependencyInjection,"src/Diten.ManagementGovernanceService.Application/DependencyInjection.cs","MOD-0355:Modules/ProcessModeling:Application");Add(process,DwsIsolationDimension.Repository,"src/Diten.ManagementGovernanceService.Persistence/Modules/ProcessModeling/ProcessModelingMongoPersistence.cs","ProcessModelingMongoRepository");Add(process,DwsIsolationDimension.CollectionIndex,"src/Diten.ManagementGovernanceService.Persistence/Modules/ProcessModeling/ProcessModelingPersistenceManifest.cs","mg_process_models");Add(process,DwsIsolationDimension.EntityBase,"src/Diten.ManagementGovernanceService.Domain/Modules/ProcessModeling/EntityBase.cs","abstract class EntityBase");Add(process,DwsIsolationDimension.Permission,"src/Diten.ManagementGovernanceService.Application/Modules/ProcessModeling/ProcessModelingPermissions.cs","management-governance.process-modeling.");Add(process,DwsIsolationDimension.AuditOutbox,"src/Diten.ManagementGovernanceService.Persistence/Modules/ProcessModeling/ProcessModelingPersistenceManifest.cs","mg_process_modeling_audit_intents");Add(process,DwsIsolationDimension.Contract,"src/Diten.ManagementGovernanceService.Application/Modules/ProcessModeling/CoreContracts.cs","IProcessModelingAtomicMutationStore");Add(process,DwsIsolationDimension.SessionTransaction,"src/Diten.ManagementGovernanceService.Persistence/Modules/ProcessModeling/ProcessModelingMongoPersistence.cs","StartTransaction");Add(process,DwsIsolationDimension.MigrationBootstrap,"src/Diten.ManagementGovernanceService.Infrastructure/Modules/ProcessModeling/CoreInfrastructureBoundary.cs","ActivatesRuntime = false");Add(process,DwsIsolationDimension.NegativeGuard,"src/Diten.ManagementGovernanceService.Domain/Modules/ProcessModeling/ProcessModels.cs","Modules.ProcessModeling");
        Add(registry,DwsIsolationDimension.ProjectGraph,"Diten.ManagementGovernanceService.sln","Diten.ManagementGovernanceService.Domain");Add(registry,DwsIsolationDimension.TypeNamespace,"src/Diten.ManagementGovernanceService.Domain/DecisionRegistry/DecisionRegistryModel.cs","Domain.DecisionRegistry");Add(registry,DwsIsolationDimension.DependencyInjection,"src/Diten.ManagementGovernanceService.Application/DependencyInjection.cs","AddDecisionRegistryApplication");Add(registry,DwsIsolationDimension.Repository,"src/Diten.ManagementGovernanceService.Persistence/DecisionRegistry/Mongo/DecisionRegistryMongoPersistence.cs","DecisionRegistryMongoRepository");Add(registry,DwsIsolationDimension.CollectionIndex,"src/Diten.ManagementGovernanceService.Persistence/DecisionRegistry/Mongo/DecisionRegistryPersistenceManifest.cs","decision_registry_records");Add(registry,DwsIsolationDimension.EntityBase,"src/Diten.ManagementGovernanceService.Domain/DecisionRegistry/DecisionRegistryModel.cs","Platform.Common.Persistence");Add(registry,DwsIsolationDimension.Permission,"src/Diten.ManagementGovernanceService.Application/DecisionRegistry/DecisionRegistryApplicationContracts.cs","DecisionRegistryPermissions");Add(registry,DwsIsolationDimension.AuditOutbox,"src/Diten.ManagementGovernanceService.Application/DecisionRegistry/DecisionRegistryApplicationContracts.cs","DecisionRegistryOutboxEntry");Add(registry,DwsIsolationDimension.Contract,"src/Diten.ManagementGovernanceService.Application/DecisionRegistry/DecisionRegistryApplicationContracts.cs","IDecisionAuthorityValidator");Add(registry,DwsIsolationDimension.SessionTransaction,"src/Diten.ManagementGovernanceService.Persistence/DecisionRegistry/Transactions/DecisionRegistryTransactionRunner.cs","CommitAsync");Add(registry,DwsIsolationDimension.MigrationBootstrap,"src/Diten.ManagementGovernanceService.Persistence/DecisionRegistry/Migrations/DecisionRegistryInitialMigration.cs","ReadOnlyInventory");Add(registry,DwsIsolationDimension.NegativeGuard,"src/Diten.ManagementGovernanceService.Domain/DecisionRegistry/DecisionRegistryModel.cs","Domain.DecisionRegistry");return result;
    }
    private static string GitShow(string checkpoint,string path){var root=FindRoot();var start=new ProcessStartInfo("git"){WorkingDirectory=root,RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false};start.ArgumentList.Add("show");start.ArgumentList.Add($"{checkpoint}:{path}");using var process=Process.Start(start)??throw new InvalidOperationException("git_show_start_failed");var output=process.StandardOutput.ReadToEnd();var error=process.StandardError.ReadToEnd();process.WaitForExit();Assert.True(process.ExitCode==0,$"{checkpoint}:{path}: {error}");return output;}
    private static string FindRoot(){var cursor=new DirectoryInfo(AppContext.BaseDirectory);while(cursor is not null&&!File.Exists(Path.Combine(cursor.FullName,"AGENTS.md")))cursor=cursor.Parent;return cursor?.FullName??throw new InvalidOperationException("repo_root_not_found");}
}
