<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../Diten.ManagementGovernanceService.Application/Diten.ManagementGovernanceService.Application.csproj" /><ProjectReference Include="../Diten.ManagementGovernanceService.Persistence/Diten.ManagementGovernanceService.Persistence.csproj" /><ProjectReference Include="../Diten.ManagementGovernanceService.Infrastructure/Diten.ManagementGovernanceService.Infrastructure.csproj" /></ItemGroup></Project>
