using Diten.Application.Dtos.EnterpriseStrategy;
using Diten.Domain.Aggregates.EnterpriseStrategy;

namespace Diten.Application.EnterpriseStrategy.Mappers;

public static class EnterpriseStrategyMappers
{
    public static GoalDto ToDto(this GoalAggregate aggregate) =>
        new()
        {
            GoalId = aggregate.Id,
            GoalTitle = aggregate.Name,
            Category = aggregate.Category,
            StrategicThemeId = aggregate.StrategicThemeId,
            GoalStatement = aggregate.Statement,
            Status = aggregate.Status,
            OwnerRole = aggregate.OwnerRole,
            OwnerCompanyId = aggregate.OwnerCompanyId,
            OwnerPersonId = aggregate.OwnerPersonId,
            StartDate = aggregate.StartDate,
            EndDate = aggregate.EndDate,
            Priority = aggregate.Priority,
            RelatedEntityScope = aggregate.RelatedEntityScope,
            EvidenceLink = aggregate.EvidenceLink,
            StrategyPeriodId = aggregate.StrategyPeriodId,
            ApplicabilityMode = aggregate.ApplicabilityMode,
            AppliesToAllCompanies = aggregate.AppliesToAllCompanies,
            ApplicableCompanyIds = aggregate.ApplicableCompanyIds,
            Version = aggregate.Version,
            DecisionReference = aggregate.DecisionReference,
            ChangeLogRef = aggregate.ChangeLogRef,
            CreatedAt = aggregate.CreatedAt,
            UpdatedAt = aggregate.UpdatedAt,
            ArchivedAt = aggregate.ArchivedAt,
            CreatedBy = aggregate.CreatedBy,
            UpdatedBy = aggregate.UpdatedBy,
            SourceTemplateType = aggregate.SourceTemplateType,
            SourceTemplateId = aggregate.SourceTemplateId,
            SourceTemplateVersion = aggregate.SourceTemplateVersion,
            SourceBlueprintPackId = aggregate.SourceBlueprintPackId,
            InstantiationBatchId = aggregate.InstantiationBatchId,
            CreatedFromLibrary = aggregate.CreatedFromLibrary,
            BudgetEnvelopes = (aggregate.YearlyBudgets ?? new()).OrderBy(x => x.Year).Select(x => new GoalYearlyBudgetEnvelopeDto
            {
                GoalId = aggregate.Id,
                Year = x.Year,
                RevenueTarget = x.RevenueTarget,
                EbitdaTarget = x.EbitdaTarget,
                CapexEnvelope = x.CapexEnvelope,
                OpexEnvelope = x.OpexEnvelope,
                SavingsTarget = x.SavingsTarget,
                FundingPool = x.FundingPool,
                Commentary = x.Commentary
            }).ToList(),
            Metrics = (aggregate.Metrics ?? new()).Select(m => new GoalMetricDto
            {
                Id = m.Id,
                MetricAssignmentId = string.IsNullOrWhiteSpace(m.MetricAssignmentId) ? m.Id : m.MetricAssignmentId,
                GoalId = m.GoalId,
                MetricDefinitionId = m.MetricDefinitionId,
                MetricName = m.MetricName,
                MetricType = m.MetricType,
                BaselineValue = m.BaselineValue,
                TargetValue = m.TargetValue,
                UnitOfMeasure = m.UnitOfMeasure,
                AggregationMethod = m.AggregationMethod,
                DirectionPolarity = m.DirectionPolarity,
                ThresholdModel = m.ThresholdModel,
                ReportingFrequency = m.ReportingFrequency,
                CascadeMetric = m.CascadeMetric,
                MetricOrigin = NormalizeMetricOrigin(m.MetricOrigin),
                MetricRole = string.IsNullOrWhiteSpace(m.MetricRole) ? "Strategic" : m.MetricRole,
                RestrictionMode = m.RestrictionMode,
                RollupEligible = m.RollupEligible,
                YearlyValues = (m.YearlyTargets ?? new()).OrderBy(x => x.Year).Select(x => new GoalMetricYearValueDto
                {
                    GoalMetricId = m.Id,
                    Year = x.Year,
                    BaselineValue = x.BaselineValue,
                    TargetValue = x.TargetValue,
                    ActualValue = x.ActualValue,
                    ForecastValue = x.ForecastValue,
                    ThresholdMin = x.ThresholdMin,
                    ThresholdMax = x.ThresholdMax,
                    Commentary = x.Commentary,
                    ThresholdCommentary = x.ThresholdCommentary
                }).ToList(),
                SortOrder = m.SortOrder,
                MetricBindingStatus = m.MetricBindingStatus,
                CreatedAt = m.CreatedAt,
                UpdatedAt = m.UpdatedAt
            }).ToList()
        };

    public static ObjectiveDto ToDto(this ObjectiveAggregate aggregate) =>
        new()
        {
            Id = aggregate.Id,
            ParentGoalId = aggregate.ParentGoalId,
            Name = aggregate.Name,
            Statement = aggregate.Statement,
            StrategicTheme = aggregate.StrategicTheme,
            Owner = aggregate.Owner,
            ExecutiveSponsor = aggregate.ExecutiveSponsor,
            ApproverId = aggregate.ApproverId,
            CoOwnerIds = aggregate.CoOwnerIds,
            ApprovalGroup = aggregate.ApprovalGroup,
            ReviewOwner = aggregate.ReviewOwner,
            ApprovalRouteType = aggregate.ApprovalRouteType,
            ApprovalStatus = aggregate.ApprovalStatus,
            Status = aggregate.Status,
            Type = aggregate.Type,
            TimeHorizonStart = aggregate.TimeHorizonStart,
            TimeHorizonEnd = aggregate.TimeHorizonEnd,
            PlanningCycle = aggregate.PlanningCycle,
            Priority = aggregate.Priority,
            ContributionType = aggregate.ContributionType,
            ContributionWeight = aggregate.ContributionWeight,
            DependencyType = aggregate.DependencyType,
            EntityScope = aggregate.EntityScope,
            BusinessUnit = aggregate.BusinessUnit,
            Region = aggregate.Region,
            DependencyNotes = aggregate.DependencyNotes,
            OwnerCompanyId = aggregate.OwnerCompanyId,
            OwnerPositionId = aggregate.OwnerPositionId,
            CurrentOwnerPersonId = aggregate.CurrentOwnerPersonId,
            PrimaryKpiMetric = aggregate.PrimaryKpiMetric,
            UnitOfMeasure = aggregate.UnitOfMeasure,
            DirectionOfPerformance = aggregate.DirectionOfPerformance,
            TargetPlanGranularity = aggregate.TargetPlanGranularity,
            ReportingFrequency = aggregate.ReportingFrequency,
            ThresholdModel = aggregate.ThresholdModel,
            DecisionReference = aggregate.DecisionReference,
            EvidenceReference = aggregate.EvidenceReference,
            InheritCompanyScope = aggregate.InheritCompanyScope,
            PrimaryCompanyId = aggregate.PrimaryCompanyId,
            ApplicableCompanyIds = aggregate.ApplicableCompanyIds,
            LinkedInitiativeIds = aggregate.LinkedInitiativeIds,
            LinkedProjectIds = aggregate.LinkedProjectIds,
            LinkedRiskIssueIds = aggregate.LinkedRiskIssueIds,
            LinkedDependencyIds = aggregate.LinkedDependencyIds,
            DependencyLinks = aggregate.DependencyLinks.Select(x => new ObjectiveDependencyLinkDto
            {
                Id = x.Id,
                DependencyTypeId = x.DependencyTypeId,
                DependencyObjectType = x.DependencyObjectType,
                DependencyReferenceId = x.DependencyReferenceId,
                DependencyReferenceText = x.DependencyReferenceText,
                DependencyCriticality = x.DependencyCriticality
            }).ToList(),
            ApprovedBy = aggregate.ApprovedBy,
            ApprovedOn = aggregate.ApprovedOn,
            EffectiveDate = aggregate.EffectiveDate,
            ReviewCadence = aggregate.ReviewCadence,
            NextReviewDate = aggregate.NextReviewDate,
            ChangeReason = aggregate.ChangeReason,
            Version = aggregate.Version,
            CreatedAt = aggregate.CreatedAt,
            UpdatedAt = aggregate.UpdatedAt,
            ArchivedAt = aggregate.ArchivedAt,
            CreatedBy = aggregate.CreatedBy,
            UpdatedBy = aggregate.UpdatedBy,
            SourceTemplateType = aggregate.SourceTemplateType,
            SourceTemplateId = aggregate.SourceTemplateId,
            SourceTemplateVersion = aggregate.SourceTemplateVersion,
            SourceBlueprintPackId = aggregate.SourceBlueprintPackId,
            InstantiationBatchId = aggregate.InstantiationBatchId,
            CreatedFromLibrary = aggregate.CreatedFromLibrary,
            AllowMultipleTargetMetrics = aggregate.AllowMultipleTargetMetrics,
            AllowRowThresholdOverrides = aggregate.AllowRowThresholdOverrides,
            YearlyBudgets = aggregate.YearlyBudgets.Select(b => new ObjectiveYearlyBudgetDto
            {
                Year = b.Year,
                RequestedBudget = b.RequestedBudget,
                ApprovedBudget = b.ApprovedBudget,
                ForecastBudget = b.ForecastBudget,
                ActualBudget = b.ActualBudget,
                VarianceAmount = b.VarianceAmount,
                Commentary = b.Commentary
            }).ToList(),
            Metrics = aggregate.Metrics.Select(x => new ObjectiveMetricDto
            {
                Id = x.Id,
                ObjectiveId = x.ObjectiveId,
                ParentMetricAssignmentId = x.ParentMetricAssignmentId,
                MetricDefId = x.MetricDefId,
                MetricClass = x.MetricClass,
                MetricRole = x.MetricRole,
                MetricName = x.MetricName,
                BaselineValue = x.BaselineValue,
                BaselineDate = x.BaselineDate,
                TargetValue = x.TargetValue,
                TargetPeriod = x.TargetPeriod,
                Direction = x.Direction,
                AggregationMethod = x.AggregationMethod,
                ThresholdTolerance = x.ThresholdTolerance,
                UnitOfMeasure = x.UnitOfMeasure,
                PolarityCode = x.PolarityCode,
                MetricBindingStatus = x.MetricBindingStatus,
                RollupEligibleFlag = x.RollupEligibleFlag,
                ThresholdModelCode = x.ThresholdModelCode,
                ReportingFrequencyCode = x.ReportingFrequencyCode,
                ContributionWeight = x.ContributionWeight,
                YearlyValues = x.YearlyValues.Select(y => new ObjectiveMetricYearValueDto
                {
                    Year = y.Year,
                    PeriodKey = y.PeriodKey,
                    PeriodLabel = y.PeriodLabel,
                    PeriodStart = y.PeriodStart,
                    PeriodEnd = y.PeriodEnd,
                    PeriodGranularity = y.PeriodGranularity,
                    SortOrder = y.SortOrder,
                    TargetValue = y.TargetValue,
                    ActualValue = y.ActualValue,
                    ForecastValue = y.ForecastValue,
                    ThresholdMin = y.ThresholdMin,
                    ThresholdMax = y.ThresholdMax,
                    Commentary = y.Commentary
                }).ToList(),
                TargetDate = x.TargetDate,
                FiscalPeriodId = x.FiscalPeriodId,
                ThresholdValue = x.ThresholdValue,
                Notes = x.Notes,
                CreatedAt = x.CreatedAt,
                UpdatedAt = x.UpdatedAt
            }).ToList()
        };

    public static StrategyConnectionDto ToDto(this StrategyConnectionAggregate aggregate) =>
        new()
        {
            Id = aggregate.Id,
            FromType = aggregate.FromType,
            FromId = aggregate.FromId,
            ToType = aggregate.ToType,
            ToId = aggregate.ToId,
            RelationshipType = aggregate.RelationshipType,
            ContributionType = aggregate.ContributionType,
            ContributionWeight = aggregate.ContributionWeight,
            MetricBindingsJson = aggregate.MetricBindingsJson,
            DecisionReferencesJson = aggregate.DecisionReferencesJson,
            EvidenceReferencesJson = aggregate.EvidenceReferencesJson,
            CompanyScopeMode = aggregate.CompanyScopeMode,
            CompanyId = aggregate.CompanyId,
            Status = aggregate.Status,
            Version = aggregate.Version,
            CreatedAt = aggregate.CreatedAt,
            UpdatedAt = aggregate.UpdatedAt,
            CreatedBy = aggregate.CreatedBy,
            UpdatedBy = aggregate.UpdatedBy,
            RetiredAt = aggregate.RetiredAt
        };

    public static PlanningCycleDto ToDto(this PlanningCycleAggregate aggregate) =>
        new()
        {
            Id = aggregate.Id,
            Code = aggregate.Code,
            Name = aggregate.Name,
            PlanningCycleType = aggregate.PlanningCycleType,
            Description = aggregate.Description,
            Status = aggregate.Status,
            OwnerCompanyId = aggregate.OwnerCompanyId,
            OwnerPositionId = aggregate.OwnerPositionId,
            CurrentOwnerPersonId = aggregate.CurrentOwnerPersonId,
            OwnerId = aggregate.OwnerId,
            EffectiveFrom = aggregate.EffectiveFrom,
            EffectiveTo = aggregate.EffectiveTo,
            CreatedOn = aggregate.CreatedOn,
            CreatedBy = aggregate.CreatedBy,
            UpdatedOn = aggregate.UpdatedOn,
            UpdatedBy = aggregate.UpdatedBy,
            ArchivedAt = aggregate.ArchivedAt
        };

    public static StrategyPeriodDto ToDto(this StrategyPeriodAggregate aggregate) =>
        new()
        {
            Id = aggregate.Id,
            PlanningCycleId = aggregate.PlanningCycleId,
            Code = aggregate.Code,
            Name = aggregate.Name,
            OwnerCompanyId = aggregate.OwnerCompanyId,
            OwnerEmployeeId = aggregate.OwnerEmployeeId,
            OwnerPositionId = aggregate.OwnerPositionId,
            CurrentOwnerPersonId = aggregate.CurrentOwnerPersonId,
            CompanyId = aggregate.CompanyId,
            BusinessUnitId = aggregate.BusinessUnitId,
            RegionId = aggregate.RegionId,
            StartDate = aggregate.StartDate,
            EndDate = aggregate.EndDate,
            ReviewCadence = aggregate.ReviewCadence,
            ScenarioType = aggregate.ScenarioType,
            VersionLabel = aggregate.VersionLabel,
            Status = aggregate.Status,
            IsDefaultForScope = aggregate.IsDefaultForScope,
            Notes = aggregate.Notes,
            CreatedOn = aggregate.CreatedOn,
            CreatedBy = aggregate.CreatedBy,
            UpdatedOn = aggregate.UpdatedOn,
            UpdatedBy = aggregate.UpdatedBy,
            ArchivedAt = aggregate.ArchivedAt
        };

    public static InitiativeStrategyLinkViewDto ToViewDto(this InitiativeStrategyLinkAggregate aggregate) =>
        new()
        {
            LinkId = aggregate.Id,
            InitiativeId = aggregate.InitiativeId,
            InitiativeName = aggregate.InitiativeName,
            Description = aggregate.Description,
            Owner = aggregate.Owner,
            DeliveryOwnerCompanyId = aggregate.DeliveryOwnerCompanyId,
            DeliveryOwnerPositionId = aggregate.DeliveryOwnerPositionId,
            DeliveryOwnerPersonId = aggregate.DeliveryOwnerPersonId,
            ExecutiveSponsor = aggregate.ExecutiveSponsor,
            AccountableSponsorRole = aggregate.AccountableSponsorRole,
            Status = aggregate.Status,
            Type = aggregate.Type,
            NormalizedType = aggregate.NormalizedType,
            StartDate = aggregate.StartDate,
            EndDate = aggregate.EndDate,
            WaveOrPhase = aggregate.WaveOrPhase,
            Priority = aggregate.Priority,
            Complexity = aggregate.Complexity,
            Maturity = aggregate.Maturity,
            PrimaryKpi = aggregate.PrimaryKpi,
            ReportingFrequency = aggregate.ReportingFrequency,
            ContributionMetricName = aggregate.ContributionMetricName,
            ContributionUnitOfMeasure = aggregate.ContributionUnitOfMeasure,
            ContributionPlanGranularity = aggregate.ContributionPlanGranularity,
            ContributionMethod = aggregate.ContributionMethod,
            ContributionTiming = aggregate.ContributionTiming,
            BenefitHypothesis = aggregate.BenefitHypothesis,
            BenefitRealizationStart = aggregate.BenefitRealizationStart,
            BenefitRealizationEnd = aggregate.BenefitRealizationEnd,
            ContributionPlanValues = aggregate.ContributionPlanValues.Select(x => new InitiativeContributionPlanValueDto
            {
                PeriodKey = x.PeriodKey,
                PeriodLabel = x.PeriodLabel,
                PeriodStart = x.PeriodStart,
                PeriodEnd = x.PeriodEnd,
                PlannedValue = x.PlannedValue,
                ActualValue = x.ActualValue,
                ForecastValue = x.ForecastValue,
                Commentary = x.Commentary
            }).ToList(),
            SourceSystem = aggregate.SourceSystem,
            SourceRecordId = aggregate.SourceRecordId,
            ParentObjectiveId = aggregate.ParentObjectiveId,
            ParentGoalId = aggregate.ParentGoalId,
            StrategyLinkStatus = aggregate.StrategyLinkStatus,
            ContributionType = aggregate.ContributionType,
            ContributionWeight = aggregate.ContributionWeight,
            MetricBindingsJson = aggregate.MetricBindingsJson,
            DecisionReference = aggregate.DecisionReference,
            EvidenceReference = aggregate.EvidenceReference,
            SponsoringCompanyId = aggregate.SponsoringCompanyId,
            ParticipatingCompanyIds = aggregate.ParticipatingCompanyIds,
            EntityScope = aggregate.EntityScope,
            InitiativeClass = aggregate.InitiativeClass,
            BudgetEnvelope = aggregate.BudgetEnvelope,
            BudgetAmount = aggregate.BudgetAmount,
            CurrencyCode = aggregate.CurrencyCode,
            FundingSource = aggregate.FundingSource,
            StrategyAlignmentNote = aggregate.StrategyAlignmentNote,
            GovernanceStage = aggregate.GovernanceStage,
            GovernanceNotes = aggregate.GovernanceNotes,
            DependencyFlag = aggregate.DependencyFlag,
            Notes = aggregate.Notes,
            Version = aggregate.Version,
            SyncedAt = aggregate.SyncedAt,
            SyncFreshness = aggregate.SyncedAt.HasValue && aggregate.SyncedAt.Value >= DateTime.UtcNow.AddHours(-24) ? "Fresh" : "Stale",
            SourceTemplateType = aggregate.SourceTemplateType,
            SourceTemplateId = aggregate.SourceTemplateId,
            SourceTemplateVersion = aggregate.SourceTemplateVersion,
            SourceBlueprintPackId = aggregate.SourceBlueprintPackId,
            InstantiationBatchId = aggregate.InstantiationBatchId,
            CreatedFromLibrary = aggregate.CreatedFromLibrary
        };

    public static ProjectStrategyLinkViewDto ToViewDto(this ProjectStrategyLinkAggregate aggregate) =>
        new()
        {
            LinkId = aggregate.Id,
            ProjectId = aggregate.ProjectId,
            ProjectName = aggregate.ProjectName,
            Description = aggregate.Description,
            OwnerPm = aggregate.OwnerPm,
            Sponsor = aggregate.Sponsor,
            BusinessOwner = aggregate.BusinessOwner,
            Status = aggregate.Status,
            Phase = aggregate.Phase,
            DeliveryType = aggregate.DeliveryType,
            DeliveryMethodology = aggregate.DeliveryMethodology,
            Priority = aggregate.Priority,
            ComplexitySize = aggregate.ComplexitySize,
            StartDate = aggregate.StartDate,
            EndDate = aggregate.EndDate,
            GoLiveDate = aggregate.GoLiveDate,
            ReportingCadence = aggregate.ReportingCadence,
            SuccessMetric = aggregate.SuccessMetric,
            MetricBaseline = aggregate.MetricBaseline,
            MetricTarget = aggregate.MetricTarget,
            RiskRating = aggregate.RiskRating,
            ReadinessStatus = aggregate.ReadinessStatus,
            OverallHealth = aggregate.OverallHealth,
            ComplianceRegulatoryImpact = aggregate.ComplianceRegulatoryImpact,
            DependencyFlag = aggregate.DependencyFlag,
            EvidenceRequiredFlag = aggregate.EvidenceRequiredFlag,
            SourceSystem = aggregate.SourceSystem,
            SourceRecordId = aggregate.SourceRecordId,
            ParentInitiativeId = aggregate.ParentInitiativeId,
            ParentInitiativeName = aggregate.ParentInitiativeName,
            ParentObjectiveId = aggregate.ParentObjectiveId,
            ParentObjectiveName = aggregate.ParentObjectiveName,
            ParentGoalId = aggregate.ParentGoalId,
            ParentGoalName = aggregate.ParentGoalName,
            ParentType = aggregate.ParentType,
            EntityScope = aggregate.EntityScope,
            CreationMode = aggregate.CreationMode,
            StrategyLinkStatus = aggregate.StrategyLinkStatus,
            ContributionNote = aggregate.ContributionNote,
            MetricBindingsJson = aggregate.MetricBindingsJson,
            DecisionReference = aggregate.DecisionReference,
            EvidenceReference = aggregate.EvidenceReference,
            DeliveryCompanyId = aggregate.DeliveryCompanyId,
            FundingCompanyId = aggregate.FundingCompanyId,
            OwningFunctionDepartment = aggregate.OwningFunctionDepartment,
            DeliveryPartnerVendor = aggregate.DeliveryPartnerVendor,
            ScopeSummary = aggregate.ScopeSummary,
            OutOfScopeNote = aggregate.OutOfScopeNote,
            BudgetRequired = aggregate.BudgetRequired,
            BudgetAmount = aggregate.BudgetAmount,
            CurrencyCode = aggregate.CurrencyCode,
            BudgetType = aggregate.BudgetType,
            BudgetBasis = aggregate.BudgetBasis,
            FundingSource = aggregate.FundingSource,
            CostCenter = aggregate.CostCenter,
            BudgetOwner = aggregate.BudgetOwner,
            ApprovalRoute = aggregate.ApprovalRoute,
            FinancialNotes = aggregate.FinancialNotes,
            NoBudgetReason = aggregate.NoBudgetReason,
            BudgetSummary = string.Empty,
            Version = aggregate.Version,
            SyncedAt = aggregate.SyncedAt,
            CreatedAt = aggregate.CreatedAt,
            UpdatedAt = aggregate.UpdatedAt,
            SyncFreshness = aggregate.SyncedAt.HasValue && aggregate.SyncedAt.Value >= DateTime.UtcNow.AddHours(-24) ? "Fresh" : "Stale",
            SourceTemplateType = aggregate.SourceTemplateType,
            SourceTemplateId = aggregate.SourceTemplateId,
            SourceTemplateName = aggregate.SourceTemplateName,
            SourceTemplateVersion = aggregate.SourceTemplateVersion,
            SourceBlueprintPackId = aggregate.SourceBlueprintPackId,
            InstantiationBatchId = aggregate.InstantiationBatchId,
            CreatedFromLibrary = aggregate.CreatedFromLibrary
        };

    private static string NormalizeMetricOrigin(string? origin)
    {
        var o = (origin ?? string.Empty).Trim();
        if (string.Equals(o, "Strategic", StringComparison.OrdinalIgnoreCase))
            return "Local";
        return string.IsNullOrWhiteSpace(o) ? "Local" : o;
    }
}
