const fs = require("fs");
const path = require("path");
const { bootSurface, app } = require("./wcn-boot");

/*
 * A1 — THE DIALOG'S VERTICAL RHYTHM IS THE PRODUCT'S (2026-08-24).
 *
 * MEASURED on /Tasks/Create, the reference form:
 *      label → field            4px   (`.form-label { margin-bottom: 4px }`, six fields, all four)
 *      field → next label      14px   ("Tahmin (saat)" → "Etiketler")
 *      label                   13px
 *
 * MEASURED in the dialogs BEFORE this round:
 *      Planla · Süre gir · Modül seç      label → field      = 19px   ✗
 *      Bilgi bekle · Yeniden ata          field → next label =  0px   ✗
 *
 * ONE CAUSE FOR THE FIRST THREE: the previous round zeroed `margin-inline` on the library's input slots and
 * left their VERTICAL margins alone — `.swal2-input` computed `margin: 15px 0 3px`, and that 15px stacked on
 * the label's own 4px. ONE CAUSE FOR THE OTHER TWO: the hand-written dialogs carried their group gap on a
 * `mb-3` sitting on the `<select>`, which select2 then hid, so the gap became nothing at all.
 */
const repoRoot = path.resolve(__dirname, "..", "..", "..");
const web = (...p) => path.join(repoRoot, "frontend", "Diten.Web", ...p);
const APP = fs.readFileSync(web("wwwroot", "assets", "js", "WorkCenterNext", "app.js"), "utf8");
const CSS = fs.readFileSync(web("wwwroot", "assets", "css", "backbone-custom.css"), "utf8");

/** The declaration block for a selector, so an assertion reads the rule and not the whole file. */
const rule = (needle) => {
  const at = CSS.indexOf(needle);
  if (at < 0) { return ""; }
  return CSS.slice(at, CSS.indexOf("}", at) + 1);
};

describe("the label owns the rhythm, and the library's slots own none of it", () => {
  it("zeroes the vertical margin the library puts on its input slots", () => {
    /*
     * MUTATION GUARD #1: remove `margin-block: 0` and this goes red — the label-to-field gap returns to 19px,
     * which is the defect the owner reported on three dialogs at once.
     */
    const r = rule(".swal2-container .swal2-modal.swal2-popup .swal2-input,");
    expect(r, "the slot rule vanished").toContain(".swal2-textarea");
    expect(r, "the library's vertical margins are back").toContain("margin-block: 0");
    // …and the previous round's horizontal fix is still there.
    expect(r).toContain("margin-inline: 0");
    expect(r).toContain("inline-size: 100%");
  });

  it("gives both kinds of label the two numbers measured off the reference form", () => {
    /*
     * MUTATION GUARD #3: set the top margin to 0 and the group gap collapses — which is the OTHER defect, the
     * one the two multi-field dialogs had.
     *
     * `.swal2-input-label` is generated by the shared component; `.form-label` is hand-written by a
     * multi-field dialog. They share popups, so they share one rule.
     */
    const r = rule(".swal2-container .swal2-modal.swal2-popup .swal2-input-label,");
    expect(r, "the two label kinds stopped sharing one rule").toContain(".swal2-html-container .form-label");
    expect(r, "the rhythm was changed or removed").toContain("margin-block: 0.875rem 0.25rem");
    // 0.25rem = 4px = the reference's own `.form-label` margin-bottom.
    // 0.875rem = 14px = the reference's rendered field→next-label gap.
  });

  it("leaves ONE mechanism owning the group gap", () => {
    // `mb-3` on the <select> was a second one, and a broken one: select2 hides the original, so it produced
    // nothing at all. Measured 0px before, 12px after — see the live table in the round's report.
    expect(APP, "a second group-gap mechanism came back").not.toContain('class="form-select mb-3"');
  });
});

describe("one action, one icon", () => {
  const ACTIONS = ["inquire", "reassign", "plan"];

  it("keeps the dictionary as the single source for the rail button and its dialog", () => {
    /*
     * MUTATION GUARD #2: name a glyph by hand in a dialog and this goes red.
     *
     * MEASURED DEFECT: the rail drew `bx-user-pin` for "Yeniden ata" while the dialog it opened drew
     * `bx-conversation` — one action, two pictures, because the dialog chose its own.
     */
    const dict = APP.slice(APP.indexOf("const inboxActionIcon"), APP.indexOf("const inboxActionIcon") + 700);
    ACTIONS.forEach((key) =>
      expect(dict, `${key} is not in the dictionary`).toContain(`${key}:`));

    // The rail button reads it…
    expect(APP).toContain("inboxActionIcon(primary)");
    /*
     * …and so does every dialog an action opens. FIVE reads: the overflow-MENU row (which was already reading
     * it), plus the four dialogs — plan, review meeting, log time, and the raw reason+assignee form.
     */
    expect((APP.match(/inboxActionIcon\(action\)/g) || []).length,
      "a dialog stopped reading the dictionary").toBe(5);
    // Three of those are the `icon:` seam; the fourth is the raw dialog's own builder call.
    expect((APP.match(/icon: inboxActionIcon\(action\)/g) || []).length).toBe(3);
  });

  it("adds a missing action TO the dictionary rather than working around it", () => {
    // Both open a dialog and neither was listed; without an entry they fell through to the generic arrow.
    const dict = APP.slice(APP.indexOf("const inboxActionIcon"), APP.indexOf("const inboxActionIcon") + 700);
    expect(dict).toContain("logTime: 'bx-time-five'");
    expect(dict).toContain("requestInfo: 'bx-question-mark'");
  });

  it("names no glyph by hand in any dialog an action opens", () => {
    ["const openDatePicker", "const openMeetingScheduler", "const openLogTime"].forEach((name) => {
      const fn = APP.slice(APP.indexOf(name), APP.indexOf(name) + 2600);
      expect(fn, `${name} hand-picked a glyph`).not.toMatch(/icon: '(bx-[a-z-]+)'/);
      expect(fn, `${name} stopped reading the dictionary`).toContain("icon: inboxActionIcon(action)");
    });
    // The reason+assignee dialog is raw, so it asks the builder directly — with the same dictionary value.
    expect(APP).toContain("dialogIcon('info', inboxActionIcon(action))");
  });

  it("leaves the two dialogs that no action opens with their own glyph", () => {
    // The snooze is a personal overlay, the module picker is a create menu — neither is an action's dialog,
    // so neither has a dictionary entry to read.
    expect(APP).toContain("icon: 'bx-moon'");
    expect(APP).toContain("icon: 'bx-cube'");
  });
});


/*
 * ⚠ WHY THERE IS NO jsdom DOM TEST FOR THE ICON MATCH, WRITTEN DOWN RATHER THAN LEFT AS AN ABSENCE.
 *
 * The glyph a reader compares is drawn on the LIST ROW's action cluster, and a row only reaches that surface
 * through the tab/admission rules (`admissionState`, `ownershipState`, the active tab). Three fixture shapes
 * were tried and none put the row on the default tab, so the test would have been asserting the fixture rather
 * than the icons. The claim is proven TWO other ways instead:
 *   · above, in the source: both surfaces call `inboxActionIcon` and no dialog names a glyph by hand;
 *   · live in the browser, for `inquire` / `reassign` / `plan` — the row button's class and the open dialog's
 *     class read back as the same string. That measurement is in the round's report.
 */

describe("the dialog's select2 is a field like the others", () => {
  /*
   * MEASURED, and it is what the owner photographed: the chosen/placeholder text rendered at **18px** while the
   * textarea beside it, and every control on the page behind, were at **15px**.
   *
   * ⚠ THE JS OPTION WAS A NO-OP. `selectionCssClass: 'form-select'` was passed and the class never arrived —
   * that key belongs to a newer select2 than this app bundles, and unknown keys are dropped in silence. The DOM
   * read back `class="select2-selection select2-selection--single"` with no `form-select` in it.
   */
  it("hooks the control with a class that actually lands, and styles it in CSS", () => {
    const fn = APP.slice(APP.indexOf("const bindDialogSelect2 ="), APP.indexOf("const bindDialogSelect2 =") + 2200);
    const code = fn.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/.*$/gm, "$1");
    expect(code, "the option that does nothing came back").not.toContain("selectionCssClass");
    expect(fn).toContain("containerCssClass: 'wcn-dialog-select'");
    // FG-003: the numbers live in the stylesheet, never inline.
    expect(CSS).toContain(".wcn-dialog-select .select2-selection__rendered");
  });

  it("writes the control at the product's own field size, not select2's", () => {
    const r = rule(".swal2-container .swal2-modal.swal2-popup .wcn-dialog-select .select2-selection__rendered");
    // 0.9375rem = 15px = `.form-control`, the same number `.wcn-date-input` already copied.
    expect(r, "the select drifted off the product's field size").toContain("font-size: 0.9375rem");
    expect(r).toContain("line-height: 36px");
    // …and the box is the product's 38px control, not select2's default.
    expect(rule(".swal2-container .swal2-modal.swal2-popup .wcn-dialog-select {")).toContain("block-size: 38px");
  });

  it("keeps the list it opens at the field's size too", () => {
    // A 15px control that opens an 18px menu is the same mismatch one step later.
    expect(CSS).toContain(".wcn-dialog-select-dropdown .select2-results__option");
  });
});
