using Xunit;
using System.Text.Json;
using Diten.SupplyChainService.Domain.Features.Returns;
using Diten.SupplyChainService.Application.Features.Returns;
using Diten.SupplyChainService.Persistence.Features.Returns;
using MongoDB.Bson;
using MongoDB.Driver;
namespace Diten.SupplyChainService.Tests.Returns;
[Collection("Returns Mongo")]
public sealed class ReturnConcurrencyTests
{
 [Theory][InlineData("6","6",1)][InlineData("4","6",2)]public async Task Create_Races_RespectsExactCap(string first,string second,int successes)
 {var f=await ReturnTestFixture.New();var result=await Task.WhenAll(f.Create(first,"one"),f.Create(second,"two"));Assert.Equal(successes,result.Count(x=>x.StatusCode==201));if(successes==1)Assert.Equal("RETURN_QUANTITY_EXCEEDED",result.Single(x=>x.StatusCode!=201).ErrorCode);Assert.Equal(successes==1?"6":"10",(await f.Entitlement())["UsedQuantity"].AsString);}
 [Fact] public async Task SameKey_TwentyConcurrentCalls_OneAggregateReceiptEvent()
 {var f=await ReturnTestFixture.New();var results=await Task.WhenAll(Enumerable.Range(0,20).Select(_=>f.Create()));Assert.All(results,x=>Assert.Equal(201,x.StatusCode));Assert.Single(results.Select(x=>x.ReturnId).Distinct());Assert.Equal(new long[]{1,1,1,1,1},await f.Counts());}
 [Theory][InlineData(ReturnStatus.Rejected)][InlineData(ReturnStatus.Cancelled)]
 public async Task Release_ReplayAndDifferentKey_DebitsExactlyOnce(ReturnStatus target)
 {var f=await ReturnTestFixture.New();var created=await f.Create("10");if(target==ReturnStatus.Cancelled)Assert.Equal(200,(await f.Transition(created.ReturnId,ReturnStatus.Authorized,"authorize")).StatusCode);Assert.Equal(200,(await f.Transition(created.ReturnId,target,"release")).StatusCode);Assert.Equal("0",(await f.Entitlement())["UsedQuantity"].AsString);Assert.True((await f.Transition(created.ReturnId,target,"release")).IdempotentReplay);Assert.Equal(422,(await f.Transition(created.ReturnId,target,"another")).StatusCode);Assert.Equal("0",(await f.Entitlement())["UsedQuantity"].AsString);Assert.Equal(201,(await f.Create("10","replacement")).StatusCode);}
 [Fact] public async Task FirstSnapshot_NumericEquivalentAllowed_DriftConflictsAtomically()
 {var f=await ReturnTestFixture.New();Assert.Equal(201,(await f.Create()).StatusCode);var before=await f.Counts();var line=f.SourceLines[0];f.SourceLines[0]=line with{Quantity="010.00"};Assert.Equal(201,(await f.Create("1","equivalent")).StatusCode);before=await f.Counts();f.SourceLines[0]=line with{Quantity="11"};var fail=await f.Create("1","drift");Assert.Equal(409,fail.StatusCode);Assert.Equal("RETURN_SOURCE_CHANGED",fail.ErrorCode);Assert.Equal(before,await f.Counts());}
 [Theory][InlineData("uom")][InlineData("item")][InlineData("sku")]
 public async Task FirstSnapshot_IdentityOrOrdinalUomDrift_Returns409(string field)
 {var f=await ReturnTestFixture.New();Assert.Equal(201,(await f.Create()).StatusCode);var before=await f.Counts();var line=f.SourceLines[0];f.SourceLines[0]=field switch{"uom"=>line with{UomId="ea"},"item"=>line with{ItemId=Guid.NewGuid()},_=>line with{SkuId=Guid.NewGuid()}};var fail=await f.Create("1","changed");Assert.Equal("RETURN_SOURCE_CHANGED",fail.ErrorCode);Assert.Equal(before,await f.Counts());}
 [Fact] public async Task ClosedAndManualReceived_RetainEntitlementOpaqueReferenceAndPendingEvents()
 {var f=await ReturnTestFixture.New();var c=await f.Create("10");foreach(var target in new[]{ReturnStatus.Authorized,ReturnStatus.InTransit,ReturnStatus.Received,ReturnStatus.Dispositioned,ReturnStatus.Closed}){var r=await f.Transition(c.ReturnId,target,target.ToString(),inventory:target==ReturnStatus.Received?"opaque-no-lookup":null,disposition:target==ReturnStatus.Dispositioned?" ":null);Assert.Equal(200,r.StatusCode);}Assert.Equal("10",(await f.Entitlement())["UsedQuantity"].AsString);Assert.Equal(1,f.Observations);Assert.Equal("RETURN_QUANTITY_EXCEEDED",(await f.Create("1","more")).ErrorCode);var auditFilter=f.Filter;auditFilter.Add("ToStatus","Received");var row=await f.Db.GetCollection<BsonDocument>("returns_audit").Find(auditFilter).FirstAsync();Assert.Equal("opaque-no-lookup",row["InventoryTransactionReferenceId"].AsString);Assert.Equal("manual-assertion",row["EvidenceType"].AsString);Assert.Equal("2026-09-20T09:00:00.123456789Z",row["OccurredAt"].AsString);var events=await f.Db.GetCollection<BsonDocument>("returns_outbox").Find(f.Filter).ToListAsync();Assert.Equal(6,events.Count);Assert.All(events,e=>Assert.Equal("Pending",e["Status"].AsString));}
 [Fact]public async Task RmaNumber_KnownCollision_MaxThreeAttemptsAndAtomicRecovery()
 {var f=await ReturnTestFixture.New();var first=await f.Create();var before=await f.Counts();for(var i=0;i<3;i++)f.Probe.Ids.Enqueue(first.ReturnId);var fail=await f.Create("1","collision");Assert.Equal(503,fail.StatusCode);Assert.Empty(f.Probe.Ids);Assert.Equal(before,await f.Counts());f.Probe.Ids.Enqueue(first.ReturnId);var fresh=Guid.NewGuid();f.Probe.Ids.Enqueue(fresh);var ok=await f.Create("1","collision");Assert.Equal(201,ok.StatusCode);Assert.Equal(fresh,ok.ReturnId);Assert.Equal("RMA-"+fresh.ToString("N").ToUpperInvariant(),ok.RmaNumber);Assert.Equal(new long[]{1,2,2,2,2},await f.Counts());}
 [Fact]public async Task Entitlement_DefaultCaseInsensitiveCollection_UsesExplicitOrdinalOperations()
 {var f=await ReturnTestFixture.New("diten_returns_collation_tests",true);var item=Guid.NewGuid();var sku=Guid.NewGuid();f.SourceLines.Clear();f.SourceLines.Add(new("A","10","EA",item,sku));f.SourceLines.Add(new("a","10","EA",item,sku));Assert.Equal(201,(await f.Create("6","upper",lines:[new("A","6","EA")])).StatusCode);Assert.Equal(201,(await f.Create("6","lower",lines:[new("a","6","EA")])).StatusCode);var rows=await f.Db.GetCollection<BsonDocument>("return_entitlements").Find(f.Filter).ToListAsync();Assert.Equal(2,rows.Count);Assert.Equal(new[]{"A","a"},rows.Select(x=>x["LineNumber"].AsString).OrderBy(x=>x,StringComparer.Ordinal));Assert.All(rows,x=>Assert.Equal("6",x["UsedQuantity"].AsString));}
}
