namespace Diten.MdmService.Domain.Enums;

public enum ProductAbbreviationHistoryEventType
{
    ALLOCATION_REQUESTED = 0,
    ALLOCATION_APPROVED = 1,
    ALLOCATION_REJECTED = 2,
    ALLOCATION_CANCELLED = 3,
    CORRECTION_REQUESTED = 4,
    CORRECTION_APPROVED = 5,
    CORRECTION_REJECTED = 6,
    CORRECTION_CANCELLED = 7,
    RETIREMENT_REQUESTED = 8,
    RETIREMENT_APPROVED = 9,
    RETIREMENT_REJECTED = 10,
    RECONCILIATION_REQUIRED = 11
}
