using Diten.Platform.Common.Persistence;
using Diten.Platform.Domain.Enums.DocumentManagement;

namespace Diten.Platform.Domain.Entities.DocumentManagement;

/// <summary>
/// MOD-0029-FU07 — immutable allocation LEDGER row for a Permanent UID or Document Code (GMG-QMS-SOP-0001 §6.3, §9.2,
/// §9.3, §12.3). Every allocation — system-generated, manually reserved, or migrated — produces exactly one ledger
/// row. The ledger is the authoritative NEVER-REUSE source: a value that appears here in ANY status (including
/// Cancelled/Abandoned) and even when soft-deleted is never handed out again. Rows are never hard-deleted; a cancel
/// is a status change only.
/// </summary>
public sealed class DocumentIdentifierAllocation : TenantScopedEntity
{
    public DocumentIdentifierType IdentifierType { get; set; }

    /// <summary>The fully formatted value, e.g. <c>UID-0000001</c> or <c>GMG-QMS-SOP-0002</c>.</summary>
    public required string IdentifierValue { get; set; }

    /// <summary>Numeric sequence component (for a manually reserved value with no numeric tail this may be null).</summary>
    public long? SequenceNumber { get; set; }

    public string? Prefix { get; set; }
    public string? DomainCode { get; set; }
    public string? TypeCode { get; set; }

    public Guid? RegisterEntryId { get; set; }
    public Guid? ControlledDocumentId { get; set; }

    public DocumentIdentifierAllocationStatus AllocationStatus { get; set; } = DocumentIdentifierAllocationStatus.Assigned;
    public DocumentIdentifierAllocationReason AllocationReason { get; set; } = DocumentIdentifierAllocationReason.NewDocument;

    /// <summary>False when the value was supplied manually (import/migration); true when generated by the engine.</summary>
    public bool IsSystemAllocated { get; set; }

    // Migration / legacy provenance (SOP §12.3).
    public string? LegacyCode { get; set; }
    public string? SourceSystem { get; set; }
    public string? SourceLegacyId { get; set; }

    public DateTimeOffset AllocatedAt { get; set; } = DateTimeOffset.UtcNow;
    public string? AllocatedBy { get; set; }

    public DateTimeOffset? CancelledAt { get; set; }
    public string? CancelledBy { get; set; }
    public string? CancellationReason { get; set; }

    public string? CorrelationId { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
}
